language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://lrae-mclauchlan.pact.dius.com.au
  # PACT_BROKER_TOKEN is encrypted below
  - secure: "kJSk0C3otW4B/VxMbUIAK9/NUhVdrm/lmRaB1lt0qGROEc1V+L/L+2+P3BsoUV+NKGJA8cUY8ZOpEdBBj+S/c60JzvNKM9tnHG5C3mtWvDbh+BnEFNILtz8oiFsHLgKR+zcNX9o1P2ktOSKPdI+J6TYeycU9lo6qybwUAjaxuUpb0msQMSX74KoVivx1MFaCGV3XYSz6xo7ysp/AHQJ6RHcuaOpYxfyJj8p8SEDe46msGeBV8etd5dYyS7gH5mirweXndiWQIjcchHEM1MH2wxGR2T3pLkCdZRgBA6jZKx0D4E9nL7I/CBZioVvs5jrBdGQ0c670epLg5sCq4vJPA0EnzWR4IsUB0IOpACePS14j2gpQL2WqcxT0dxGiVrM1jrmOgRkNxBkEJW6bJVVVPafC7ettsSW5WGHYbC2mkgibbCJm6BpZtpTSNA3ZDGisLlUg+lbKNtO7+e08CzD9R17SMSt7fyjgV8hfNWxojVL3TgfSfdtkv7FDddFA0WIxW/2bxXKWqUyGu4i+9HBMVs5djvDtPgfImDYGnBbfy1CFN1JhZZYcPaRjj2MQKMWBXwo8/UMHydAg3xqC5IAtLLHjgIIvvmef/AiopZdCqaCxrLlNPdR/gGEnBtyqeO7wTQ/or/zs7GEDXOpeH0CaSllVQZeSk90ld+/FftzIKzw="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
